name: module4_task0
permissions:
  contents: write
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: main
  schedule:
    - cron: '0 13 * * *'
jobs:
  module4_task0:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: setup
        run: bash module4_task0/setup.sh
        shell: bash
      - name: Build and create package
        run: |
          cd module4_task0
          make package
      - name: Lint
        run: |
          cd module4_task0
          make lint
      - name: Integration-tests
        run: |
          cd module4_task0
          make build
          make validate
          make integration-tests
          make unit-tests
          make clean
      - name: Archive package
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: upload-package
          path: module4_task0/awesome-website.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 1.0.0
          files: |
            module4_task0/awesome-website.zip
            module4_task0/DEPLOY.md
