name: module3_task0
on:
  push:
    branches: main
  schedule:
    - cron: '0 13 * * *'
jobs: 
  module3_task0
    build:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout repository
         uses: actions/checkout@v2
        - name: Run make help
          run: |
              cd module3_task0/
            make help
