name: module3_task0
on:
  push:
    branches: main
  schedule:
    - cron: '0 13 * * *'
jobs:
  module3_task0:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: setup
        run:  bash setup.sh
      - name: build
        run: |
          cd module3_task1/
          make build 
